project:
  type: website
  output-dir: build

execute: 
  enabled: true

website:
  favicon: /img/logo_niu_light.png
  site-url: "https://dashboard.neuroinformatics.dev"
  navbar:
    right:
      - href: https://github.com/neuroinformatics-unit/dashboard
        icon: github
        target: _blank
    left:
      - href: index.qmd
        text: Dashboard
      - href: about.qmd
        text: About

format:
  html:
    theme:
      light: [niu-light.scss, brand]
      dark: [niu-dark.scss, brand]
    toc: true
    page-layout: full
    mainfont: "Barlow"
    monofont: "JetBrains Mono"
